---
# build server setup
- name: install maven
  hosts: build
  become: yes

  tasks:
  - name: Ensure default-jdk package is installed
    apt:
      pkg:
      - default-jdk
      - maven
      - git
      state: present

# building war
- name: build war
  hosts: build
  become: yes

  tasks:
  - name: clone files from Git repository
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse

  - name: package war
    shell:
      chdir: /tmp/boxfuse
      cmd: mvn package

# app server setup
- name: install tomcat
  hosts: app
  become: yes

  tasks:
  - name: Ensure tomcat9 package is installed
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat9 service is started
    service:
      name: tomcat9
      state: started

# launching war
- name: sync war from build server
  hosts: all
  become: yes

  tasks:
  - name: push artifact from build server
    synchronize:
      src: /tmp/boxfuse/target/hello-1.0.war
      dest: rsync://app/var/lib/tomcat9/webapps/hello-1.0.war
    delegate_to: build
      