---
# build server setup
- name: install maven
  hosts: build
  become: yes

tasks: Update cache
   apt:
     update_cache: yes

tasks:
  - name: Ensure default-jdk package is installed
    apt:
      name: default-jdk
      state: present

tasks:
  - name: Ensure maven package is installed
    apt:
      name: maven
      state: present

# building war
- name: build war
  hosts: build
  become: yes

tasks:
  - name: clone files from Git repository
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/

tasks:
  - name: package war
    shell:
      chdir: /tmp/boxfuse
      cmd: mvn package

# app server setup
- name: install tomcat
  hosts: app
  become: yes

tasks: Update cache
   apt:
     update_cache: yes

tasks:
  - name: Ensure tomcat9 package is installed
    apt:
      name: tomcat9
      state: present

tasks:
  - name: Ensure tomcat9 service is started
    service:
      name: tomcat9
      state: started

# launching war
- name: Copy war from build to app server
  hosts: app
  become: yes

tasks:
  - name: Copy war to tomcat folder
    synchronize:
      mode: push
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: rsync://app/usr/local/tomcat9/webapps/
    delegate_to: build